### ISSUE TITLE
any plan to build opencore 0.7.9 

### ISSUE THREAD

**Issue by fowlmouse** [Zisbusy/MSI-B460M-MORTAR-MAC#1]
as subject :)

**Comment by Zisbusy** [comment]
当OpenCore 0.7.5 不能满足最新的 Mac OS 版本时，我将会升级 OpenCore 与驱动。目前 Mac OS 12.3 测试未发现问题。

**Comment by Zisbusy** [comment]
已经升级 OpenCore 0.8.0
