### ISSUE TITLE
能不能帮忙做一个支持独显RX5700XT 的配直档案 

### ISSUE THREAD

**Issue by fowlmouse** [Zisbusy/MSI-B460M-MORTAR-MAC#2]
你好 请问是否可以帮忙制作一个支持独显的config 档案 谢谢

**Comment by Zisbusy** [comment]
现在的配置支持免驱动显卡直接驱动

**Comment by fowlmouse** [comment]
谢谢回覆 根据回覆是否可以这样理解 只要改三码 其它不动 即可驱动RX5700XT 对吗？如果是 我空了试试看

Zisbusy ***@***.***> 於 2022年6月14日 週二 上午8:21寫道：

**Comment by Zisbusy** [comment]
试过驱动R9 380，直接插上就能识别。

**Comment by Zisbusy** [comment]
![0830D606-27C7-4EE7-96CB-7DE8CF0F6D33](https://user-images.githubusercontent.com/49525016/173774576-de3d7a74-b1e9-4031-9fba-212de9ea6ebb.png)

**Comment by Zisbusy** [comment]
![0830D606-27C7-4EE7-96CB-7DE8CF0F6D33](https://user-images.githubusercontent.com/49525016/173774738-51506136-b7d5-4646-8d88-5d04f37d6b0b.png)

**Comment by fowlmouse** [comment]
好的 谢谢！ 我空了试试看！

Zisbusy ***@***.***> 於 2022年6月15日 週三 下午4:00寫道：
