### ISSUE TITLE
大佬，啥时候更新

### ISSUE THREAD

**Issue by MarshKent** [Zisbusy/MSI-B460M-MORTAR-MAC#3]

**Comment by Zisbusy** [comment]
目前版本测试 12.6 没问题，或许等到13正式版才更新吧

**Comment by MarshKent** [comment]
正式版出了，我按现有的更新，一直重启。期待大佬更新OC。

**Comment by Zisbusy** [comment]
> 正式版出了，我按现有的更新，一直重启。期待大佬更新OC。

有计划了，近期更新。

**Comment by Zisbusy** [comment]
已经更新，测试可用。

**Comment by MarshKent** [comment]
效率太高了，谢大佬引导

**Comment by EvanLin1003** [comment]
测试的大佬们 休眠唤醒可正常

**Comment by Zisbusy** [comment]
> 测试的大佬们 休眠唤醒可正常

基本正常。

**Comment by JCXIE** [comment]
> > 测试大佬们休眠唤醒可正常>>基本正常。支持鼠标键盘唤醒不

**Comment by EvanLin1003** [comment]
支持鼠标键盘唤醒不

**Comment by EvanLin1003** [comment]
大佬用了你这个EFI 休眠是直接关机。然后蓝牙不能用了。 和你一样的无线设备啊

**Comment by Zisbusy** [comment]
> 大佬用了你这个EFI 休眠是直接关机。然后蓝牙不能用了。 和你一样的无线设备啊

已经修复，请再次测试。
