### ISSUE TITLE
显卡

### ISSUE THREAD

**Issue by Sword6988** [Zisbusy/MSI-B460M-MORTAR-MAC#4]
6600xt显卡是否可以使用

**Comment by Zisbusy** [comment]
没有测试过

**Comment by Sword6988** [comment]
> 没有测试过

你这个文件是否有添加对于5500xt独显的优化文件

**Comment by Zisbusy** [comment]
近期的提交已经移除5500xt的相关优化文件
https://github.com/Zisbusy/MSI-B460M-MORTAR-MAC/archive/refs/heads/master.zip

**Comment by Sword6988** [comment]
> 近期的提交已经移除5500xt的相关优化文件 https://github.com/Zisbusy/MSI-B460M-MORTAR-MAC/archive/refs/heads/master.zip

那就好，6600xt默认是免驱的，我测试一下6600xt是不是可以使用

**Comment by Zisbusy** [comment]
测试后麻烦反馈下

**Comment by Sword6988** [comment]
嗯，这种优化文件是否确实有效果，还是纯属心理作用？

**Comment by Zisbusy** [comment]
“国光”有一篇文章，提到了，基本没用。
https://apple.sqlsec.com/6-%E5%AE%9E%E7%94%A8%E5%A7%BF%E5%8A%BF/6-9/

**Comment by Sword6988** [comment]
大佬你这个引导是不是不支持windows加mac双系统啊，我用黑果小兵的镜像写入U盘，用你的efi文件替换oc分区之后，无法进入安装界面，总是自动进入了win系统

**Comment by Zisbusy** [comment]
支持，
